# 在运行构建之前需要先执行docker pull opencloudos/opencloudos:8.8
# 构建时执行 docker build --rm -t graalvm-opencloudos . --file docs/dev-ops/Dockerfile-opencloudos
FROM opencloudos/opencloudos:8.8

RUN yum update -y && yum install -y gcc zlib-devel curl bash tar findutils
# Support for Network
# RUN yum -y install httpd; yum clean all; systemctl enable httpd.service
# EXPOSE 80

# ENV PS1="\u@\h:\w\$"

RUN cd /root
# Install GraalVM
RUN curl -4 -L https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_linux-x64_bin.tar.gz -o graalvm.tar.gz
RUN tar -xzf graalvm.tar.gz
RUN rm graalvm.tar.gz
RUN export GRAALVM_NAME=$(find . -maxdepth 1 -type d -name "graalvm-jdk*" -printf "%f\n") && \
	mv "${GRAALVM_NAME}" graalvm-jdk-21 && \
	mv graalvm-jdk-21 /usr/local/
ENV JAVA_HOME="/usr/local/graalvm-jdk-21"
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# Install Maven
RUN curl -4 -L https://repo.huaweicloud.com:8443/artifactory/apache-local/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz -o apache-maven-3.9.6-bin.tar.gz
RUN tar -xzf apache-maven-3.9.6-bin.tar.gz
RUN rm apache-maven-3.9.6-bin.tar.gz
RUN mv apache-maven-3.9.6 /usr/local/apache-maven-3.9.6
ENV PATH="/usr/local/apache-maven-3.9.6/bin:${PATH}"

# Mirrors of Maven
RUN mkdir -p /root/.m2 && \
    echo '<?xml version="1.0" encoding="UTF-8"?>\
<settings xmlns="http://maven.apache.org/SETTINGS/1.2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">\
    <mirrors>\
        <mirror>\
            <id>aliyunmaven</id>\
            <mirrorOf>*</mirrorOf>\
            <name>阿里云公共仓库</name>\
            <url>https://maven.aliyun.com/repository/public</url>\
        </mirror>\
    </mirrors>\
</settings>' > /root/.m2/settings.xml
